project: STALE INVITE PLS UPDATE Ansible Security Automation working group
meeting_id: security
project_url: https://github.com/ansible/community/wiki/Security-Automation
agenda_url: https://github.com/ansible/community/issues?q=is:open+label:meeting_agenda+label:security
chair: Adam Miller (maxamillion), Sumit Jaiswal (justjais), Abhijeet Kasurde (akasurde)
description: |

  See https://github.com/ansible-community/meetings/tree/main for updated invite.
schedule:
- time: '1500'
  day: Monday
  irc: ansible-security or https://matrix.to/#/#security-automation:ansible.com
  frequency: weekly
