project: STALE INVITE PLS UPDATE
meeting_id: 
project_url:
agenda_url: 
chair: 
description: |

  See https://github.com/ansible-community/meetings/tree/main for updated invite.
schedule:
- time: '1500'
  day: Monday
  irc: ansible-security or https://matrix.to/#/#security-automation:ansible.com
  frequency: weekly
